// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVzJNgVcUIKos51P0yRRh_KXO3bgH6xpk',
    appId: '1:198576614116:web:6ca6721ea10e2de4721af1',
    messagingSenderId: '198576614116',
    projectId: 'emergencyserviceapp-aec43',
    authDomain: 'emergencyserviceapp-aec43.firebaseapp.com',
    storageBucket: 'emergencyserviceapp-aec43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrVOtDz7jg6Bg4U8Fstae4rszGDGew1bY',
    appId: '1:198576614116:android:a733115dcd8d539f721af1',
    messagingSenderId: '198576614116',
    projectId: 'emergencyserviceapp-aec43',
    storageBucket: 'emergencyserviceapp-aec43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm0baoWHPtU8WymI-u9DvxWunlmCzU8fk',
    appId: '1:198576614116:ios:08e463a559550e83721af1',
    messagingSenderId: '198576614116',
    projectId: 'emergencyserviceapp-aec43',
    storageBucket: 'emergencyserviceapp-aec43.appspot.com',
    iosClientId: '198576614116-o93u206d0m03f3d51mvre4fc98i1ug16.apps.googleusercontent.com',
    iosBundleId: 'com.example.emergencyServiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm0baoWHPtU8WymI-u9DvxWunlmCzU8fk',
    appId: '1:198576614116:ios:08e463a559550e83721af1',
    messagingSenderId: '198576614116',
    projectId: 'emergencyserviceapp-aec43',
    storageBucket: 'emergencyserviceapp-aec43.appspot.com',
    iosClientId: '198576614116-o93u206d0m03f3d51mvre4fc98i1ug16.apps.googleusercontent.com',
    iosBundleId: 'com.example.emergencyServiceApp',
  );
}
